export const API = {
  PARTNER_STORE: "/partner-store",
  BUSINESS_INFORMTAION: "/business-information",
  STORE_FEATURE: "/store-feature",
  OPTION_PRODUCT: "/option-product",
  TOURIST_SPOT: "/tourist-spot",
  STORE_TERMS: "/store-terms",
  ROOM_TYPE: "/room-type",
  ROOM: "/room",
  SEASON: "/season",
  ROOM_RATE: "/room-rate",
  CODE: "/code",
  ADMIN: "/admin",
  AUTHENTICATION: "/authentication/refresh-token",
  HEALTH_CHECK: "/healthCheck",
};
