"use client";
// import "./globals.css";
// import "../styles/globals.css";
import "@/styles/globals.scss";
import "@/styles/room-detail-modal.scss";
import "@/styles/consulting.scss";
import "@/styles/our-stay.scss";
import "@/styles/login.scss";
import "@/styles/sign-up.scss";
import "@/styles/reservation-check.scss";
import "@/styles/reservation-information.scss";
import "@/styles/menu-bar.scss";
import "slick-carousel";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import styled from "styled-components";
import Script from "next/script";
// import "react-kakao-maps-sdk";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BodyContainer>
        <div className="header_continer">
          <Navbar />
        </div>
        <main>{children}</main>
        <div id="modal-root"></div>
        <FooterContainer>
          <Footer />
        </FooterContainer>
        <link
          rel="preconnect"
          as="image"
          href="https://stay-interview.s3.amazonaws.com/stayinterviewLogo.png"
        />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" />.
        {/* <Script src="https://developers.kakao.com/sdk/js/kakao.js" async /> */}
        {/* <Script
          strategy="beforeInteractive"
          type="text/javascript"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=a98d4c1b2d78b9d4e9ab8a8adc84a85b&autoload=false&libraries=services`}
        ></Script> */}
        {/* <Script
          strategy="beforeInteractive"
          type="text/javascript"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAOMAP_APPKEY}&autoload=false&libraries=services`}
        ></Script> */}
        {/* <script src="https://pay.nicepay.co.kr/v1/js/"></script> */}
        {/* <Script
          src="https://pg-web.nicepay.co.kr/v3/common/js/nicepay-pgweb.js"
          type="text/javascript"
        ></Script> */}
        {/* <script src="https://pg-web.nicepay.co.kr/v3/common/js/nicepay-pgweb.js"></script> */}
      </BodyContainer>
    </html>
  );
}

const BodyContainer = styled.body`
  width: 100%;
  overflow: auto;
  background: #f6f5f1;
`;

// const HeaderContainer = styled.header`
//   position: absolute;
//   width: 100%;
//   // width: 100%;
//   // position: sticky;
//   top: 0;
//   /* background-color: #162318;
//   opacity: 0.5; */
//   z-index: 10;
// `;

const FooterContainer = styled.footer`
  background-color: #203d1e;
`;
