"use client";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import styled from "styled-components";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BodyContainer>
        <HeaderContainer>
          <Navbar />
        </HeaderContainer>
        <main>{children}</main>
        <FooterContainer>
          <Footer />
        </FooterContainer>
      </BodyContainer>
    </html>
  );
}

const BodyContainer = styled.body`
  width: 100%;
  overflow: auto;
  background: #f6f5f1;
`;

const HeaderContainer = styled.header`
  position: sticky;
  top: 0;
  /* background-color: #162318;
  opacity: 0.5; */
  z-index: 10;
`;

const FooterContainer = styled.footer`
  background-color: #203d1e;
`;
